# CONFIG FILE

title: DevOps ATC POLAND
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: SotiriosVrachas/jekyll-theme-startbootstrap-agency
plugins:
  - jekyll-feed
  - jekyll-remote-theme

