brand:
  name: DevOps
menu-string: Menu

nav:
  - title: Cooperation
    url: '#cooperation'
  - title: Propositions
    url: '#portfolio'
  - title: Repositories & ALM
    url: '#repo'
  - title: Benefits
    url: '#plus'
  - title: Principles
    url: '#capacity'
  - title: Experts
    url: '#people'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; Accenture 2018  | All rights reserved

reponame:
  phab: https://www.phacility.com/pricing/ 
  bitbucket: https://bitbucket.org/product/pricing 
  gitlab: https://about.gitlab.com/pricing/#gitlab-com 
  github: https://github.com/pricing 
  vsts: https://www.visualstudio.com/team-services/pricing/ 
  jiraatl: https://www.atlassian.com/software/jira/pricing 
